#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
from typing import Any, Dict, Iterable, List
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from office.mission_command.e24_ecosystem_archaeology import build_ceo_brain_state,build_ceo_control_room,build_ceo_execution_router,build_commercial_imagination_paths,build_czl_closure,build_duplicate_overlap_map,build_ecosystem_alignment_gate,build_ecosystem_route_registry,build_entity_resolution,build_evidence_index,build_existing_wheel_inventory,build_field_functional_opportunity_map,build_future_ceo_agent_policy,build_innovation_hypotheses,build_kg,build_legacy_ceo_brain_adapter,build_legacy_ceo_brain_archaeology,build_mature_pattern_borrowing_matrix,build_missing_wheel_analysis,build_promotion_candidates,build_read_model,build_repo_modification_decision_packet,build_revenue_path_portfolio_selection,build_strategic_memory_promotion_gate,build_whole_ecosystem_observation

def write_json(path: Path, data: Dict[str, Any]) -> None: path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> None: path.parent.mkdir(parents=True,exist_ok=True); path.write_text("".join(json.dumps(r,ensure_ascii=False)+"\n" for r in rows),encoding="utf-8")
def write_text(path: Path, text: str) -> None: path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding="utf-8")
def md(title: str, bullets: Iterable[str]) -> str: return "# "+title+"\n\n"+"\n".join(f"- {b}" for b in bullets)+"\n"

def create_e24(repo_root: Path, output_root: Path) -> List[str]:
    observation=build_whole_ecosystem_observation(); inventory=build_existing_wheel_inventory(); overlaps=build_duplicate_overlap_map(); archaeology=build_legacy_ceo_brain_archaeology(); adapter=build_legacy_ceo_brain_adapter(archaeology); missing=build_missing_wheel_analysis(); mature=build_mature_pattern_borrowing_matrix(); kg=build_kg(archaeology,adapter); entity_resolution=build_entity_resolution(kg); evidence_index=build_evidence_index(kg); read_model=build_read_model(kg); promotion_candidates=build_promotion_candidates(kg); field_map=build_field_functional_opportunity_map(); imagination=build_commercial_imagination_paths(); innovation=build_innovation_hypotheses(); selection=build_revenue_path_portfolio_selection(field_map,imagination); brain=build_ceo_brain_state(read_model,selection); router=build_ceo_execution_router(selection); memory_gate=build_strategic_memory_promotion_gate(kg,promotion_candidates); route_registry=build_ecosystem_route_registry(); alignment=build_ecosystem_alignment_gate(observation,inventory); repo_decision=build_repo_modification_decision_packet(); future_policy=build_future_ceo_agent_policy(); control_room=build_ceo_control_room(observation,inventory,overlaps,missing,read_model,brain,field_map,imagination,innovation,selection,router,alignment); closure=build_czl_closure(observation,archaeology,inventory,missing,read_model,brain,imagination,alignment)
    json_outputs={"operations/external_validation/e24_whole_ecosystem_observation.json":observation,"operations/external_validation/e24_existing_wheel_inventory.json":inventory,"operations/external_validation/e24_duplicate_overlap_map.json":overlaps,"operations/external_validation/e24_legacy_ceo_brain_archaeology.json":archaeology,"operations/external_validation/e24_legacy_ceo_brain_adapter.json":adapter,"operations/external_validation/e24_missing_wheel_analysis.json":missing,"operations/external_validation/e24_mature_pattern_borrowing_matrix.json":mature,"operations/external_validation/e24_ceo_brain_state.json":brain,"operations/external_validation/e24_field_functional_opportunity_map.json":field_map,"operations/external_validation/e24_commercial_imagination_paths.json":imagination,"operations/external_validation/e24_innovation_hypotheses.json":innovation,"operations/external_validation/e24_revenue_path_portfolio_selection.json":selection,"operations/external_validation/e24_ceo_execution_router.json":router,"operations/external_validation/e24_strategic_memory_promotion_gate.json":memory_gate,"operations/external_validation/e24_ecosystem_route_registry.json":route_registry,"operations/external_validation/e24_ceo_control_room.json":control_room,"operations/external_validation/e24_ecosystem_alignment_gate.json":alignment,"operations/external_validation/e24_repo_modification_decision_packet.json":repo_decision,"operations/external_validation/e24_future_ceo_agent_policy.json":future_policy,"operations/external_validation/e24_czl_closure.json":closure,"operations/knowledge_graph/e24_ceo_kg_evidence_index.json":evidence_index,"operations/knowledge_graph/e24_ceo_kg_entity_resolution.json":entity_resolution,"operations/knowledge_graph/e24_ceo_kg_read_model.json":read_model,"operations/knowledge_graph/e24_ceo_kg_promotion_candidates.json":promotion_candidates}
    for rel,data in json_outputs.items(): write_json(output_root/rel,data)
    write_jsonl(output_root/"operations/knowledge_graph/e24_ceo_kg_nodes.jsonl",kg["nodes"]); write_jsonl(output_root/"operations/knowledge_graph/e24_ceo_kg_edges.jsonl",kg["edges"])
    md_outputs={
      "operations/external_validation/e24_ceo_control_room.md":md("E24 CEO Control Room",[f"repos_scanned: {observation['repos_scanned_count']}",f"legacy_ceo_brain_found: {str(observation['local_legacy_ceo_brain_found']).lower()}",f"existing_wheels_reused: {inventory['reused_wheel_count']}",f"KG nodes: {read_model['node_count']}",f"KG edges: {read_model['edge_count']}",f"top_selected_path: {selection['top_selected_path']['id']}",f"strategic_bottleneck: {brain['current_strategic_bottleneck']}",f"recommended_next_milestone: {router['recommended_next_milestone']}","external_action_executed: false"]),
      "reports/integration/e24_whole_ecosystem_ceo_kg_brain_runtime.md":md("E24 Whole Ecosystem CEO KG Brain Runtime",["Created an evidence-bound CEO knowledge graph and working/shadow CEO commercial brain.","Legacy CEO assets were routed as historical/candidate knowledge, not current truth.","No provider API, send, publication, payment, or live receipt occurred."]),
      "reports/integration/e24_whole_ecosystem_observation.md":md("E24 Whole Ecosystem Observation",[f"repos_scanned: {observation['repos_scanned_count']}",f"local_legacy_ceo_brain_found: {observation['local_legacy_ceo_brain_found']}",f"missing_critical_wheels: {len(observation['missing_critical_wheels'])}"]),
      "reports/integration/e24_existing_wheel_inventory.md":md("E24 Existing Wheel Inventory",[f"wheel_count: {inventory['wheel_count']}",f"reused_wheel_count: {inventory['reused_wheel_count']}"]),
      "reports/integration/e24_duplicate_overlap_map.md":md("E24 Duplicate Overlap Map",[f"overlap_cluster_count: {overlaps['overlap_cluster_count']}","destructive_refactor_performed: false"]),
      "reports/integration/e24_legacy_ceo_brain_archaeology.md":md("E24 Legacy CEO Brain Archaeology",[f"found: {archaeology['local_legacy_ceo_brain_found']}",f"items_count: {archaeology['items_count']}","direct_canonical_promotion: false"]),
      "reports/integration/e24_missing_wheel_analysis.md":md("E24 Missing Wheel Analysis",[f"missing_wheels_identified: {missing['missing_wheels_identified']}",f"implemented_now_count: {missing['implemented_now_count']}"]),
      "reports/integration/e24_mature_pattern_borrowing_matrix.md":md("E24 Mature Pattern Borrowing Matrix",[f"pattern_count: {mature['pattern_count']}",f"fresh_external_research_performed: {mature['fresh_external_research_performed']}"]),
      "reports/integration/e24_ceo_knowledge_graph.md":md("E24 CEO Knowledge Graph",[f"node_count: {read_model['node_count']}",f"edge_count: {read_model['edge_count']}",f"evidence_bound_node_count: {evidence_index['evidence_bound_node_count']}",f"legacy_derived_node_count: {evidence_index['legacy_derived_node_count']}",f"generated_hypothesis_node_count: {evidence_index['generated_hypothesis_node_count']}"]),
      "reports/integration/e24_field_functional_opportunity_map.md":md("E24 Field Functional Opportunity Map",[f"opportunity_nodes_count: {field_map['opportunity_nodes_count']}",f"top_opportunity: {field_map['ranked_opportunities'][0]['opportunity_id']}"]),
      "reports/integration/e24_commercial_imagination_paths.md":md("E24 Commercial Imagination Paths",[f"path_count: {imagination['path_count']}","all_paths_are_hypotheses: true"]),
      "reports/integration/e24_innovation_hypotheses.md":md("E24 Innovation Hypotheses",[f"innovation_hypotheses_count: {innovation['innovation_hypotheses_count']}","generated_hypothesis_not_fact: true"]),
      "reports/integration/e24_revenue_path_portfolio_selection.md":md("E24 Revenue Path Portfolio Selection",[f"top_selected_path: {selection['top_selected_path']['id']}",f"backup_paths: {len(selection['backup_paths'])}",f"blocked_paths: {len(selection['blocked_paths'])}"]),
      "reports/integration/e24_ceo_execution_router.md":md("E24 CEO Execution Router",[f"autonomous_actions_recommended: {len(router['autonomous_actions_recommended'])}",f"owner_approval_required_by_risk: {len(router['owner_approval_actions_required_by_risk'])}",f"blocked_no_go_actions: {len(router['blocked_no_go_actions'])}"]),
      "reports/integration/e24_ecosystem_route_registry.md":md("E24 Ecosystem Route Registry",[f"route_count: {route_registry['route_count']}","duplicate_wheel_prevention: enabled"]),
      "reports/integration/e24_ecosystem_alignment_gate.md":md("E24 Ecosystem Alignment Gate",[f"repos_checked: {len(alignment['repos_checked'])}",f"closure_status: {alignment['closure_status']}",f"gov_mcp_modified: {alignment['gov_mcp_modified']}"]),
      "reports/integration/e24_future_ceo_agent_policy.md":md("E24 Future CEO Agent Policy",[f"requirements: {len(future_policy['future_commercial_milestone_requirements'])}","owner_manual_send_default_allowed: false"]),
      "reports/integration/e24_czl_closure.md":md("E24 CZL Closure",[f"Y*: {closure['Y_star']}",f"Rt+1: {closure['Rt_plus_1']}",f"repos_scanned: {closure['repos_scanned']}",f"kg_node_count: {closure['kg_node_count']}",f"kg_edge_count: {closure['kg_edge_count']}",f"no_real_external_action_occurred: {closure['no_real_external_action_occurred']}",f"no_provider_api_called: {closure['no_provider_api_called']}",f"no_message_sent: {closure['no_message_sent']}"])}
    for rel,text in md_outputs.items(): write_text(output_root/rel,text)
    return sorted(list(json_outputs)+["operations/knowledge_graph/e24_ceo_kg_nodes.jsonl","operations/knowledge_graph/e24_ceo_kg_edges.jsonl"]+list(md_outputs))
def main():
    p=argparse.ArgumentParser(); p.add_argument("--repo-root",default="."); p.add_argument("--output-root",default="."); p.add_argument("--json",action="store_true"); a=p.parse_args(); files=create_e24(Path(a.repo_root),Path(a.output_root)); res={"status":"created","file_count":len(files),"files":files}; print(json.dumps(res,indent=2) if a.json else f"created {len(files)} E24 files")
if __name__=="__main__": main()
