#!/usr/bin/env python3
"""
External Signal Ingestion — CEO's window to the outside world.

Fetches:
- Source A: Our 3 repos GitHub activity (stars/issues/PRs/releases/commits)
- Source B: GitHub trending in agents/governance space
- Source C: (stub) arxiv RSS / customer email / Slack

Outputs: reports/external_signals_$(date).md
Emits: CIEU EXTERNAL_SIGNAL_INGESTED
"""

import json
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Union, Optional


def gh_api(endpoint: str) -> Optional[Union[dict, list]]:
    """Call gh api, return parsed JSON or None on error."""
    try:
        result = subprocess.run(
            ["gh", "api", endpoint, "--cache", "1h"],
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
        else:
            print(f"gh api {endpoint} failed: {result.stderr}", file=sys.stderr)
            return None
    except Exception as e:
        print(f"gh_api exception for {endpoint}: {e}", file=sys.stderr)
        return None


def fetch_repo_activity(owner: str, repo: str) -> dict:
    """Fetch GitHub activity for one repo."""
    repo_data = gh_api(f"repos/{owner}/{repo}") or {}

    # Get latest release
    releases = gh_api(f"repos/{owner}/{repo}/releases?per_page=1") or []
    latest_release = releases[0]["tag_name"] if releases else "none"

    # Get recent commits (last 7 days)
    week_ago = (datetime.now() - timedelta(days=7)).isoformat()
    commits = gh_api(f"repos/{owner}/{repo}/commits?since={week_ago}") or []

    # Get open issues & PRs
    issues = gh_api(f"repos/{owner}/{repo}/issues?state=open&per_page=100") or []
    prs = [i for i in issues if "pull_request" in i]
    pure_issues = [i for i in issues if "pull_request" not in i]

    return {
        "name": f"{owner}/{repo}",
        "stars": repo_data.get("stargazers_count", 0),
        "open_issues": len(pure_issues),
        "open_prs": len(prs),
        "latest_release": latest_release,
        "commits_last_7d": len(commits),
        "last_push": repo_data.get("pushed_at", "unknown")
    }


def fetch_trending_agents() -> list:
    """Fetch trending repos in agents/governance space."""
    week_ago = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")

    # Search agents + LLM-agent topics
    queries = [
        f"search/repositories?q=topic:agents+language:python+pushed:>{week_ago}&sort=stars&per_page=10",
        f"search/repositories?q=topic:llm-agent+pushed:>{week_ago}&sort=stars&per_page=10"
    ]

    trending = []
    seen_names = set()

    for query in queries:
        result = gh_api(query)
        if result and "items" in result:
            for item in result["items"]:
                name = item["full_name"]
                if name not in seen_names:
                    seen_names.add(name)
                    trending.append({
                        "name": name,
                        "stars": item.get("stargazers_count", 0),
                        "description": item.get("description", "")[:100],
                        "url": item.get("html_url", "")
                    })

    # Sort by stars, top 10
    trending.sort(key=lambda x: x["stars"], reverse=True)
    return trending[:10]


def generate_report(our_repos: list, trending: list) -> str:
    """Generate markdown report."""
    today = datetime.now().strftime("%Y-%m-%d")

    md = f"""# External Signals Report — {today}

## Our Repositories Activity

"""

    for repo in our_repos:
        md += f"""### {repo['name']}
- **Stars**: {repo['stars']}
- **Open Issues**: {repo['open_issues']}
- **Open PRs**: {repo['open_prs']}
- **Latest Release**: {repo['latest_release']}
- **Commits (7d)**: {repo['commits_last_7d']}
- **Last Push**: {repo['last_push']}

"""

    md += """## GitHub Trending (Agents/Governance)

"""

    for i, repo in enumerate(trending, 1):
        md += f"""{i}. **{repo['name']}** ({repo['stars']} ⭐)
   - {repo['description']}
   - {repo['url']}

"""

    md += """## Other Signals (Stub)

### arXiv RSS
- **Status**: Not yet integrated
- **Target topics**: multi-agent systems, LLM governance, agent coordination

### Customer Email
- **Status**: Not yet integrated
- **Target sources**: sales@ybridgelabs.ai, support@ybridgelabs.ai

### Slack/Community
- **Status**: Not yet integrated
- **Target channels**: Y*gov discussions, agent governance communities

---
*Generated by external_signals.py*
"""

    return md


def emit_cieu(changeset: dict):
    """Emit CIEU event for signal ingestion."""
    try:
        from ystar.kernel.engine import get_engine
        engine = get_engine()
        engine.emit_cieu_event(
            "EXTERNAL_SIGNAL_INGESTED",
            "scripts.external_signals",
            changeset=changeset
        )
    except Exception as e:
        print(f"CIEU emit failed (non-blocking): {e}", file=sys.stderr)


def main():
    """Main entry point."""
    print("🌍 Fetching external signals...")

    # Source A: Our repos
    our_repo_specs = [
        ("liuhaotian2024-prog", "ystar-bridge-labs"),
        ("liuhaotian2024-prog", "Y-star-gov"),
        ("liuhaotian2024-prog", "gov-mcp")
    ]

    our_repos = []
    for owner, repo in our_repo_specs:
        print(f"  Fetching {owner}/{repo}...")
        activity = fetch_repo_activity(owner, repo)
        our_repos.append(activity)

    # Source B: Trending
    print("  Fetching trending agents/governance repos...")
    trending = fetch_trending_agents()

    # Generate report
    report = generate_report(our_repos, trending)

    # Write to reports/
    reports_dir = Path(__file__).parent.parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    today = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"external_signals_{today}.md"
    report_path.write_text(report)

    print(f"✅ Report written to {report_path}")

    # Emit CIEU
    changeset = {
        "our_repos": our_repos,
        "trending_count": len(trending),
        "trending_top_3": [t["name"] for t in trending[:3]],
        "report_path": str(report_path)
    }
    emit_cieu(changeset)

    # Output trending repo names for tech_radar integration
    trending_names = [t["name"] for t in trending]
    trending_file = reports_dir / f"external_signals_{today}_trending.json"
    trending_file.write_text(json.dumps(trending_names, indent=2))
    print(f"✅ Trending list written to {trending_file}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
