#!/bin/bash
# K9 Daily Patrol — orchestrator
# Trigger: daily 06:00 via cron
# Board approval: 2026-04-15 K9 v2 Task 4 (Samantha as Secretary)
# Spec: reports/k9_upgrade_daily_patrol_spec_20260415.md
#
# 4 steps:
#   1) k9_cieu_export   — export last 24h CIEU events to K9 JSONL
#   2) k9_repo_audit    — 3-repo residue scan (rule 1-5, rule 6-10 pending)
#   3) k9_digest        — summarize top-5 actionable → reports/k9_daily/{YYYYMMDD}.md
#   4) BOARD_PENDING push — append link under "K9 Daily Findings" section
#
# Fail-policy: soft-fail per step (log + continue). Final digest path always written.

set -u
export YSTAR_AGENT_ID=k9-patrol

YSTAR_DIR="/Users/haotianliu/.openclaw/workspace/ystar-company"
K9_DIR="/Users/haotianliu/.openclaw/workspace/K9Audit"
DATE=$(date +%Y%m%d)
TS=$(date +%Y-%m-%dT%H:%M:%S%z)
OUT_DIR="$YSTAR_DIR/reports/k9_daily"
DIGEST="$OUT_DIR/${DATE}.md"
LOG="/tmp/k9_daily_patrol.log"
EXPORT_JSONL="/tmp/k9_cieu_export_${DATE}.jsonl"
AUDIT_TXT="$YSTAR_DIR/reports/k9_repo_audit_${DATE}.txt"
BOARD_PENDING="$YSTAR_DIR/BOARD_PENDING.md"

mkdir -p "$OUT_DIR"

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG"; }

log "=== K9 Daily Patrol start $TS ==="

# Step 1: CIEU export
log "Step 1/4 — k9_cieu_export.py"
if [ -f "$YSTAR_DIR/scripts/k9_cieu_export.py" ]; then
    /usr/bin/python3 "$YSTAR_DIR/scripts/k9_cieu_export.py" \
        --since 24h --out "$EXPORT_JSONL" >> "$LOG" 2>&1 \
        && log "  exported → $EXPORT_JSONL ($(wc -l < "$EXPORT_JSONL" 2>/dev/null || echo 0) events)" \
        || log "  WARN: export failed (non-fatal)"
else
    log "  SKIP: k9_cieu_export.py missing"
fi

# Step 2: repo audit (company only for v1; Y-gov / gov-mcp in v2)
log "Step 2/4 — k9_repo_audit.py on ystar-company"
if [ -f "$K9_DIR/k9_repo_audit.py" ]; then
    cd "$YSTAR_DIR" && /usr/bin/python3 "$K9_DIR/k9_repo_audit.py" \
        --path "$YSTAR_DIR" > "$AUDIT_TXT" 2>&1 \
        && log "  audit → $AUDIT_TXT ($(grep -c '^\[' "$AUDIT_TXT" 2>/dev/null || echo 0) findings)" \
        || log "  WARN: audit exited non-zero (findings may still be recorded)"
else
    log "  SKIP: k9_repo_audit.py missing at $K9_DIR"
fi

# Step 3: digest — synthesize top-5 actionable
log "Step 3/4 — digest → $DIGEST"
{
    echo "# K9 Daily Patrol — $DATE"
    echo ""
    echo "**Run**: $TS"
    echo "**Agent**: k9-patrol (cron 06:00)"
    echo ""
    echo "## Top findings (top 30 lines from repo audit)"
    echo ""
    echo '```'
    if [ -f "$AUDIT_TXT" ]; then
        head -30 "$AUDIT_TXT"
    else
        echo "(no audit output this cycle)"
    fi
    echo '```'
    echo ""
    echo "## CIEU export summary"
    echo ""
    if [ -f "$EXPORT_JSONL" ]; then
        COUNT=$(wc -l < "$EXPORT_JSONL" 2>/dev/null || echo 0)
        echo "- events exported (24h): $COUNT"
        echo "- file: \`$EXPORT_JSONL\`"
    else
        echo "- (no CIEU export this cycle)"
    fi
    echo ""
    echo "## Raw artifacts"
    echo ""
    echo "- repo audit: \`$AUDIT_TXT\`"
    echo "- cieu jsonl: \`$EXPORT_JSONL\`"
    echo "- log: \`$LOG\`"
    echo ""
    echo "## Pending upgrades (spec §2)"
    echo ""
    echo "- [ ] rule 6-10 (ORPHAN_PROCESS / UNTRACKED_CRITICAL / HARDCODED_PATH / FAIL_OPEN_SURGE / MULTI_CLONE) — Maya"
    echo "- [ ] causal DAG schema adapter — Leo"
    echo "- [ ] digest severity classifier P0-P3 — Jordan"
    echo ""
    echo "---"
    echo "_Auto-generated by \`scripts/k9_daily_patrol.sh\`. Board approved 2026-04-15._"
} > "$DIGEST"
log "  digest written ($(wc -l < "$DIGEST") lines)"

# Step 4: BOARD_PENDING push
log "Step 4/4 — BOARD_PENDING append"
if [ -f "$BOARD_PENDING" ]; then
    if ! grep -q "^## K9 Daily Findings" "$BOARD_PENDING"; then
        log "  section header missing — skipped (bootstrap handled out-of-band by Samantha)"
    else
        {
            echo ""
            echo "### $DATE — K9 patrol digest"
            echo ""
            echo "- digest: \`reports/k9_daily/${DATE}.md\`"
            echo "- findings: $(grep -c '^\[' "$AUDIT_TXT" 2>/dev/null || echo 0) repo-audit items"
            echo "- run: $TS"
        } >> "$BOARD_PENDING"
        log "  entry appended under 'K9 Daily Findings'"
    fi
else
    log "  WARN: BOARD_PENDING.md not found"
fi

log "=== K9 Daily Patrol done ==="
exit 0
