#!/usr/bin/env python3.11
"""
update_gap_map.py — GOV-010 Phase 4

Scans knowledge/{role}/role_definition/task_type_map.md and checks
which task types have corresponding theory library files in
knowledge/{role}/theory/. Outputs a gap_map.md with three statuses:

  ✅ 已完整  — theory/{task_type}.md exists and has >5 lines
  🟡 部分完成 — theory/{task_type}.md exists but has ≤5 lines
  🔴 完全空白 — no theory file for this task type

Usage:
  python3.11 scripts/update_gap_map.py               # all roles
  python3.11 scripts/update_gap_map.py --actor cto    # single role
"""
import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROLES = ["ceo", "cto", "cmo", "cso", "cfo", "secretary"]


def to_snake(name: str) -> str:
    return re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "_", name.lower().strip()).strip("_")


def scan_role(role: str) -> dict:
    role_dir = REPO_ROOT / "knowledge" / role
    task_map = role_dir / "role_definition" / "task_type_map.md"
    theory_dir = role_dir / "theory"

    if not task_map.exists():
        return {"role": role, "error": "task_type_map.md not found", "types": []}

    text = task_map.read_text()
    task_names = re.findall(r"^## \d+\.\s+(.+)$", text, re.MULTILINE)

    theory_files = {}
    if theory_dir.exists():
        for f in theory_dir.iterdir():
            if f.suffix == ".md" and f.name != "README.md":
                lines = len(f.read_text().strip().split("\n"))
                theory_files[f.stem.lower()] = lines

    types = []
    for name in task_names:
        snake = to_snake(name)
        if snake in theory_files:
            lines = theory_files[snake]
            status = "complete" if lines > 5 else "partial"
        elif name.lower() in theory_files:
            lines = theory_files[name.lower()]
            status = "complete" if lines > 5 else "partial"
        else:
            status = "empty"
            lines = 0
        types.append({"name": name, "snake": snake, "status": status, "lines": lines})

    return {"role": role, "types": types, "error": None}


def write_gap_map(role: str, result: dict):
    out_path = REPO_ROOT / "knowledge" / role / "role_definition" / "gap_map.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    STATUS_ICON = {"complete": "✅", "partial": "🟡", "empty": "🔴"}

    lines = [
        f"# {role.upper()} — Theory Library Gap Map",
        "",
        f"Auto-generated by `scripts/update_gap_map.py`. Do not edit manually.",
        "",
        "| # | Task Type | Status | Theory Lines |",
        "|---|-----------|--------|--------------|",
    ]

    complete = partial = empty = 0
    for i, t in enumerate(result["types"], 1):
        icon = STATUS_ICON[t["status"]]
        lines.append(f"| {i} | {t['name']} | {icon} {t['status']} | {t['lines']} |")
        if t["status"] == "complete":
            complete += 1
        elif t["status"] == "partial":
            partial += 1
        else:
            empty += 1

    total = len(result["types"])
    lines += [
        "",
        f"**Summary**: {total} task types — "
        f"✅ {complete} complete, 🟡 {partial} partial, 🔴 {empty} empty",
        f"**Coverage**: {(complete + partial) / max(total, 1) * 100:.0f}%",
    ]

    out_path.write_text("\n".join(lines) + "\n")
    return out_path, complete, partial, empty


def main():
    p = argparse.ArgumentParser(description="Generate theory library gap maps")
    p.add_argument("--actor", default=None, help="Single role (default: all)")
    args = p.parse_args()

    roles = [args.actor] if args.actor else ROLES

    for role in roles:
        result = scan_role(role)
        if result.get("error"):
            print(f"  {role}: {result['error']}")
            continue
        path, c, pa, e = write_gap_map(role, result)
        total = len(result["types"])
        print(f"  {role}: {total} types — ✅{c} 🟡{pa} 🔴{e} → {path.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
