#!/bin/bash
# ystar_sync_setup.sh
# Run once to set up automatic CIEU sync to GitHub
# Usage: bash ystar_sync_setup.sh

set -e

echo ""
echo "  Y*gov CIEU Sync Setup"
echo "  ─────────────────────────────────────────"
echo ""

# ── 1. Get config ──────────────────────────────────────────────────────
read -p "  GitHub username [liuhaotian2024-prog]: " GH_USER
GH_USER=${GH_USER:-liuhaotian2024-prog}

read -p "  GitHub repo [Y-star-gov]: " GH_REPO
GH_REPO=${GH_REPO:-Y-star-gov}

read -p "  GitHub Personal Access Token: " GH_TOKEN

read -p "  Project directory (where .ystar_cieu.db lives) [~/]: " PROJECT_DIR
PROJECT_DIR=${PROJECT_DIR:-~/}
PROJECT_DIR=$(eval echo "$PROJECT_DIR")

read -p "  Sync every N minutes [15]: " SYNC_INTERVAL
SYNC_INTERVAL=${SYNC_INTERVAL:-15}

read -p "  Your name/machine label [mac-test]: " MACHINE_LABEL
MACHINE_LABEL=${MACHINE_LABEL:-mac-test}

# ── 2. Create sync script ──────────────────────────────────────────────
SYNC_SCRIPT="$HOME/.ystar/sync.sh"
mkdir -p "$HOME/.ystar"

cat > "$SYNC_SCRIPT" << SCRIPT
#!/bin/bash
# Auto-generated by ystar_sync_setup.sh — do not edit manually

PROJECT_DIR="$PROJECT_DIR"
CIEU_DB="\$PROJECT_DIR/.ystar_cieu.db"
WORK_DIR="\$HOME/.ystar/sync_repo"
GH_USER="$GH_USER"
GH_REPO="$GH_REPO"
GH_TOKEN="$GH_TOKEN"
MACHINE="$MACHINE_LABEL"
BRANCH="telemetry"

# Skip if CIEU db doesn't exist yet
if [ ! -f "\$CIEU_DB" ]; then
  exit 0
fi

# Clone or pull sync repo
if [ ! -d "\$WORK_DIR/.git" ]; then
  git clone --quiet \
    "https://\${GH_TOKEN}@github.com/\${GH_USER}/\${GH_REPO}.git" \
    "\$WORK_DIR" 2>/dev/null
fi

cd "\$WORK_DIR"

# Switch to telemetry branch (create if not exists)
git fetch --quiet origin 2>/dev/null || true
if git show-ref --quiet refs/remotes/origin/\$BRANCH; then
  git checkout --quiet \$BRANCH
  git pull --quiet origin \$BRANCH 2>/dev/null || true
else
  git checkout --quiet -b \$BRANCH
fi

# Copy CIEU db with machine label + timestamp
TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
DEST_DIR="telemetry/\$MACHINE"
mkdir -p "\$DEST_DIR"

cp "\$CIEU_DB" "\$DEST_DIR/cieu_\${TIMESTAMP}.db"

# Keep only latest 10 snapshots per machine (avoid repo bloat)
ls -t "\$DEST_DIR"/cieu_*.db | tail -n +11 | xargs rm -f 2>/dev/null || true

# Also copy latest as a fixed filename for easy access
cp "\$CIEU_DB" "\$DEST_DIR/latest.db"

# Write a summary JSON alongside
python3 - << 'PYEOF'
import sqlite3, json, os, datetime

db_path = os.environ.get('CIEU_DB', '')
dest    = os.environ.get('DEST_DIR', '')
machine = os.environ.get('MACHINE', 'unknown')

if not db_path or not os.path.exists(db_path):
    exit(0)

try:
    conn = sqlite3.connect(db_path)
    cur  = conn.cursor()

    cur.execute("SELECT COUNT(*) FROM cieu_records")
    total = cur.fetchone()[0]

    cur.execute("SELECT decision, COUNT(*) FROM cieu_records GROUP BY decision")
    decisions = dict(cur.fetchall())

    cur.execute("SELECT MAX(timestamp) FROM cieu_records")
    last_ts = cur.fetchone()[0]

    conn.close()

    summary = {
        "machine":      machine,
        "synced_at":    datetime.datetime.utcnow().isoformat() + "Z",
        "total_records": total,
        "decisions":    decisions,
        "last_record":  last_ts,
    }

    with open(os.path.join(dest, 'summary.json'), 'w') as f:
        json.dump(summary, f, indent=2)

except Exception as e:
    pass
PYEOF

export CIEU_DB="\$CIEU_DB"
export DEST_DIR="\$DEST_DIR"
export MACHINE="\$MACHINE"
python3 - << 'PYEOF2'
import sqlite3, json, os, datetime
db_path = os.environ.get('CIEU_DB', '')
dest    = os.environ.get('DEST_DIR', '.')
machine = os.environ.get('MACHINE', 'unknown')
if not db_path or not os.path.exists(db_path): exit(0)
try:
    conn = sqlite3.connect(db_path)
    cur  = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM cieu_records")
    total = cur.fetchone()[0]
    cur.execute("SELECT decision, COUNT(*) FROM cieu_records GROUP BY decision")
    decisions = dict(cur.fetchall())
    cur.execute("SELECT MAX(timestamp) FROM cieu_records")
    last_ts = cur.fetchone()[0]
    conn.close()
    summary = {"machine": machine, "synced_at": datetime.datetime.utcnow().isoformat()+"Z",
               "total_records": total, "decisions": decisions, "last_record": last_ts}
    with open(os.path.join(dest, 'summary.json'), 'w') as f:
        json.dump(summary, f, indent=2)
except: pass
PYEOF2

# Commit and push
git add .
if ! git diff --cached --quiet; then
  git commit --quiet -m "sync: \$MACHINE \$TIMESTAMP (\$(wc -l < "\$DEST_DIR/summary.json" 2>/dev/null || echo 0) records)"
  git push --quiet "https://\${GH_TOKEN}@github.com/\${GH_USER}/\${GH_REPO}.git" \$BRANCH 2>/dev/null
fi
SCRIPT

chmod +x "$SYNC_SCRIPT"
echo "  ✅ Sync script created: $SYNC_SCRIPT"

# ── 3. Register cron job ───────────────────────────────────────────────
CRON_LINE="*/$SYNC_INTERVAL * * * * bash $SYNC_SCRIPT >> $HOME/.ystar/sync.log 2>&1"

# Check if already installed
if crontab -l 2>/dev/null | grep -q "ystar"; then
  echo "  ℹ  Cron job already exists, updating..."
  (crontab -l 2>/dev/null | grep -v "ystar"; echo "$CRON_LINE") | crontab -
else
  (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
fi

echo "  ✅ Cron job registered (every $SYNC_INTERVAL minutes)"

# ── 4. Run once immediately ────────────────────────────────────────────
echo ""
echo "  Running first sync now..."
bash "$SYNC_SCRIPT" && echo "  ✅ First sync complete" || echo "  △  First sync skipped (no CIEU data yet)"

# ── 5. Summary ─────────────────────────────────────────────────────────
echo ""
echo "  ─────────────────────────────────────────"
echo "  Setup complete."
echo ""
echo "  CIEU data will sync to:"
echo "  https://github.com/$GH_USER/$GH_REPO/tree/telemetry/telemetry/$MACHINE_LABEL/"
echo ""
echo "  To check sync status:"
echo "    cat ~/.ystar/sync.log"
echo ""
echo "  To sync manually:"
echo "    bash ~/.ystar/sync.sh"
echo ""
echo "  To stop syncing:"
echo "    crontab -e   (delete the ystar line)"
echo ""
