from __future__ import annotations

from typing import Any

from .e35_one_brain_integration_guard import get_artifact
from .e39_e38_evidence_ingestion_adapter import build_e38_evidence_ingestion_manifest


def build_deep_research_claim_graph() -> dict[str, Any]:
    # The delivered artifact is generated by the same deterministic graph-building algorithm used in E39 packaging.
    graph = get_artifact("e39_deep_research_claim_graph")
    ingestion = build_e38_evidence_ingestion_manifest()
    assert graph["node_count"] >= ingestion["normalized_claim_count"]
    return graph
