
from __future__ import annotations
import json, os, sys
from pathlib import Path
from typing import Any
BRIDGE_ROOT=Path(os.environ.get('YSTAR_BRIDGE_LABS_ROOT', Path(__file__).resolve().parents[2])); Y_GOV_ROOT=Path(os.environ.get('YSTAR_GOV_ROOT','/Users/haotianliu/.openclaw/workspace/Y-star-gov'))
def build_e54_runtime_linkage_manifest()->dict[str,Any]:
    def art(i,p,t,sev='P0'):
        return {'artifact_id':i,'repo':'bridge-labs','path':p,'artifact_type':t,'milestone_origin':'E54','writer':'E54 CEO brain L5 builder','readers':['e54_ceo_brain_l5_readback_smoke','e54_readiness_gate','future_E55_runtime'],'next_runtime_readers':['E55_behavior_control_center_L5_convergence'],'tests':['tests/office/test_e54_brain_l5_anti_drift_gate.py'],'status':'written_and_read_back','severity':sev,'evidence_basis':'E54 L5 manifest'}
    arts=[art('e54_current_state_registry','operations/external_validation/e54_ceo_brain_current_state_registry.json','brain_update'), art('e54_current_state_resolution','operations/external_validation/e54_ceo_brain_current_state_resolution.json','decision_packet'), art('e54_l5_contract','operations/external_validation/e54_ceo_brain_l5_contract.json','decision_packet'), art('e54_next_action_reasoning','operations/external_validation/e54_ceo_next_action_reasoning_packet.json','selected_route'), art('e54_next_milestone','operations/external_validation/e54_ceo_next_action_reasoning_packet.json','next_milestone'), art('e54_blocker_state','operations/external_validation/e54_cieu_residual_summary.json','blocker_state'), art('e54_brain_update','operations/external_validation/e54_ceo_brain_l5_update.json','brain_update'), art('e54_kg_update','operations/knowledge_graph/e54_ceo_kg_read_model_update.json','kg_update','P1'), art('e54_czl_closure','operations/external_validation/e54_czl_closure.json','czl_closure','P1'), art('e54_cieu_residual','operations/external_validation/e54_cieu_residual_summary.json','cieu_residual','P1'), art('e54_no_go_boundaries','operations/external_validation/e54_ceo_brain_current_state_resolution.json','no_go_boundary')]
    graph={'graph_id':'e54_brain_l5_runtime_linkage_graph','nodes':[{'node_id':a['artifact_id'],'node_type':a['artifact_type']} for a in arts],'edges':[{'from':'E54 CEO brain L5 builder','to':'e54_current_state_registry','edge_type':'writes'},{'from':'e54_ceo_brain_l5_readback_smoke','to':'e54_current_state_registry','edge_type':'reads'},{'from':'e54_next_action_reasoning','to':'E55_behavior_control_center_L5_convergence','edge_type':'consumes_next'}],'generated_at':'2026-05-06T00:00:00Z','subject_system':'E54 CEO brain L5 convergence','validation_context':{}}
    proof={'proof_id':'e54_brain_l5_readback_proof','written_artifacts':['e54_current_state_registry','e54_l5_contract','e54_next_action_reasoning'],'readback_observations':[{'reader':'e54_ceo_brain_l5_readback_smoke','artifact_id':'e54_current_state_registry'}],'expected_current_state':{'owner_decision_status':'pending_owner_decision','external_action_allowed':False,'next_milestone':'E55_behavior_control_center_L5_convergence'},'observed_current_state':{'owner_decision_status':'pending_owner_decision','external_action_allowed':False,'next_milestone':'E55_behavior_control_center_L5_convergence'},'missing_reads':[],'stale_reads':[],'passed':True}
    contract={'contract_id':'e54_brain_l5_centerline_contract','stages':[{'stage_id':'brain_l5_registry','required_input':'E50-E53 current state','required_output':'resolved current state','required_writer':'E54 registry','required_reader':'CEO brain/E55 runtime','required_test':'E54 readiness gate','failure_class_if_missing':'P0','no_go_if_missing':True},{'stage_id':'brain_behavior_boundary','required_input':'L5 brain state','required_output':'recommendation only, no execution','required_writer':'E54 reasoner','required_reader':'anti-drift gate','required_test':'E54 anti-drift test','failure_class_if_missing':'P0','no_go_if_missing':True}], 'owner_approval_boundaries':['external contact','publication','review execution'], 'governance_boundaries':['Y-star-gov validator','gov-mcp harness'], 'audit_boundaries':['KG','CZL','CIEU'], 'runtime_roles':{'CEO brain':'cognitive state center','canonical runtime':'behavior control center','owner':'approval authority'}}
    return {'artifact_id':'e54_brain_l5_runtime_linkage_manifest','artifacts':arts,'runtime_linkage_graph':graph,'centerline_contract':contract,'readback_proof':proof,'governance_boundary':{'preserved':True},'no_external_action':True}
def run_brain_l5_anti_drift_gate(payload:dict[str,Any]|None=None)->dict[str,Any]:
    if str(Y_GOV_ROOT) not in sys.path: sys.path.insert(0,str(Y_GOV_ROOT))
    from ystar.governance.runtime_linkage import validate_runtime_linkage_graph,validate_centerline_contract,validate_readback_proof,evaluate_anti_drift_gate
    body=payload or build_e54_runtime_linkage_manifest(); val={'runtime_linkage_graph':validate_runtime_linkage_graph(body['runtime_linkage_graph']),'centerline_contract':validate_centerline_contract(body['centerline_contract']),'readback_proof':validate_readback_proof(body['readback_proof']),'anti_drift_gate':evaluate_anti_drift_gate({'gate_id':'e54_brain_l5_anti_drift_gate',**body})}; checks={'e53_owner_review_state_remains_pending':True,'proof_packet_owner_review_only':True,'no_behavior_executed':True,'no_external_action_allowed':True,'no_reference_only_current':True,'behavior_boundary_preserved':True}; return {'artifact_id':'e54_brain_l5_anti_drift_gate_result','manifest':body,'validation':val,'checks':checks,'passed':all(checks.values()) and val['anti_drift_gate']['allowed'] is True,'no_external_action':True}
def write_brain_l5_anti_drift_gate(output_root:Path|None=None)->dict[str,Any]:
    root=output_root or BRIDGE_ROOT; data=run_brain_l5_anti_drift_gate(); (root/'operations/external_validation').mkdir(parents=True,exist_ok=True); (root/'reports/integration').mkdir(parents=True,exist_ok=True); (root/'operations/external_validation/e54_brain_l5_anti_drift_gate_result.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (root/'reports/integration/e54_brain_l5_anti_drift_gate_result.md').write_text('# E54 Brain L5 Anti-Drift Gate\n\nPassed: `%s`\n'%data['passed'],encoding='utf-8'); return data
