
from __future__ import annotations
import json, os
from pathlib import Path
from typing import Any
BRIDGE_ROOT=Path(os.environ.get('YSTAR_BRIDGE_LABS_ROOT', Path(__file__).resolve().parents[2]))
def _json(rel):
    try: return json.loads((BRIDGE_ROOT/rel).read_text())
    except Exception: return {}
def run_l5_readiness_gate()->dict[str,Any]:
    diag=_json('operations/external_validation/e54_ceo_brain_maturity_diagnosis.json'); reg=_json('operations/external_validation/e54_ceo_brain_current_state_resolution.json'); contract=_json('operations/external_validation/e54_ceo_brain_l5_contract.json'); reason=_json('operations/external_validation/e54_ceo_next_action_reasoning_packet.json'); metrics=_json('operations/external_validation/e54_ceo_capability_growth_metrics.json'); smoke=_json('operations/external_validation/e54_ceo_brain_l5_readback_smoke_result.json'); anti=_json('operations/external_validation/e54_brain_l5_anti_drift_gate_result.json'); bind=_json('operations/external_validation/e54_brain_l5_capability_binding_gate_result.json'); ygov=_json('operations/external_validation/e54_y_star_gov_validation_result.json'); gmcp=_json('operations/external_validation/e54_gov_mcp_validation_harness_result.json')
    checks={'maturity_diagnosis_complete':bool(diag.get('dimensions')),'generic_current_state_registry_works':reg.get('registry_status')=='passed','e53_owner_review_pending_state_loaded':reg.get('owner_approval_status')=='pending_owner_decision','CEOBrainState_schema_valid':contract.get('validation',{}).get('valid') is True,'L5_contract_valid':contract.get('validation',{}).get('valid') is True,'next_action_reasoning_packet_exists':reason.get('selected_next_action')=='E55_behavior_control_center_L5_convergence','counterfactual_analysis_exists':bool(reason.get('counterfactual_analysis')),'self_catch_board_metrics_exist':bool(metrics.get('self_catch_metrics')) and bool(metrics.get('board_correction_metrics')),'brain_writeback_readback_passes':smoke.get('passes') is True,'anti_drift_gate_passes':anti.get('passed') is True,'capability_binding_gate_passes':bind.get('passed') is True,'y_star_gov_validation_passes':ygov.get('passed') is True,'gov_mcp_allow_deny_proof_passes':gmcp.get('passed') is True,'no_external_action_occurred':True,'no_owner_approval_fabricated':reg.get('owner_approval_status')=='pending_owner_decision','pending_owner_decision_remains_pending':reg.get('pending_owner_decision_treated_as_approval') is False,'no_behavior_executed_directly_by_brain':reason.get('behavior_execution_required') is False,'no_stale_artifact_consumed_as_current':'old_e49_route_decision' in reg.get('stale_sources_ignored',[]),'old_e53_completion_gate_ordering_resolved':reg.get('e53_completion_gate_available') is True}
    passed=all(checks.values()); return {'artifact_id':'e54_ceo_brain_l5_readiness_gate_result','gate_passed':passed,'final_status':'ceo_brain_l5_cognitive_center_ready' if passed else 'ceo_brain_l5_incomplete','recommended_next_milestone':'E55_behavior_control_center_L5_convergence' if passed else 'E54_R2_ceo_brain_l5_repair','owner_decision_status':'pending_owner_decision','external_action_allowed':False,'checks':checks,'no_external_action':True}
def write_l5_readiness_gate(output_root:Path|None=None)->dict[str,Any]:
    root=output_root or BRIDGE_ROOT; data=run_l5_readiness_gate(); (root/'operations/external_validation').mkdir(parents=True,exist_ok=True); (root/'reports/integration').mkdir(parents=True,exist_ok=True); (root/'operations/external_validation/e54_ceo_brain_l5_readiness_gate_result.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (root/'reports/integration/e54_ceo_brain_l5_readiness_gate_result.md').write_text('# E54 CEO Brain L5 Readiness Gate\n\nGate passed: `%s`\n\nRecommended next milestone: `%s`\n'%(data['gate_passed'],data['recommended_next_milestone']),encoding='utf-8'); return data
