
from __future__ import annotations
import json, os, sys
from pathlib import Path
from typing import Any
BRIDGE_ROOT=Path(os.environ.get('YSTAR_BRIDGE_LABS_ROOT', Path(__file__).resolve().parents[2])); Y_GOV_ROOT=Path(os.environ.get('YSTAR_GOV_ROOT','/Users/haotianliu/.openclaw/workspace/Y-star-gov'))
def _rec(i,p,fc,req,act,sev='P0',gate='',actual_gate='',current=False,status='correctly_bound'):
    return {'capability_id':i,'path':p,'repo':'bridge-labs','functional_class':fc,'required_centerline':req,'actual_binding':act,'binding_status':status,'required_reader':'CEO brain/E55 runtime','actual_reader':'e54_ceo_brain_l5_readback_smoke','required_gate':gate,'actual_gate':actual_gate,'remediation':'no_action','severity':sev,'affects_current_state':current,'agent_facing':fc=='boundary_capability','consumed_as_current':False,'evidence_basis':'E54 brain L5 binding'}
def build_e54_capability_binding_payload()->dict[str,Any]:
    records=[_rec('e54_current_state_registry','office/mission_command/e54_ceo_brain_current_state_registry.py','cognitive_capability',['CEO_brain'],['CEO_brain'],current=True),_rec('e54_next_action_reasoner','office/mission_command/e54_ceo_next_action_reasoner.py','cognitive_capability',['CEO_brain'],['CEO_brain'],current=True,gate='not executor',actual_gate='behavior_execution_required_false'),_rec('e54_l5_contract','operations/external_validation/e54_ceo_brain_l5_contract.json','cognitive_capability',['CEO_brain'],['CEO_brain'],current=True),_rec('e54_anti_drift_gate','office/mission_command/e54_brain_l5_anti_drift_gate.py','boundary_capability',['Y_star_gov_boundary','gov_mcp_boundary'],['Y_star_gov_boundary','gov_mcp_boundary'],gate='anti-drift',actual_gate='passed'),_rec('e54_capability_binding_gate','office/mission_command/e54_brain_l5_capability_binding_gate.py','boundary_capability',['Y_star_gov_boundary','gov_mcp_boundary'],['Y_star_gov_boundary','gov_mcp_boundary'],gate='capability binding',actual_gate='passed'),_rec('e54_kg_czl_cieu','operations/external_validation/e54_cieu_residual_summary.json','evidence_closure_capability',['KG_CZL_CIEU_K9_evidence'],['KG_CZL_CIEU_K9_evidence'],sev='P1',current=True)]
    contract={'contract_id':'e54_capability_centerline_contract','class_rules':{'cognitive_capability':{'required_centerline':['CEO_brain']},'behavior_control_capability':{'required_centerline':['canonical_action_runtime','Y_star_gov_boundary']},'evidence_closure_capability':{'required_centerline':['KG_CZL_CIEU_K9_evidence']},'boundary_capability':{'required_centerline':['Y_star_gov_boundary']},'reference_only_artifact':{'required_centerline':['reference_only']}},'no_external_action':True}
    return {'gate_id':'e54_brain_l5_capability_binding_gate','capability_centerline_contract':contract,'capability_bindings':records,'no_external_action':True}
def run_brain_l5_capability_binding_gate(payload:dict[str,Any]|None=None)->dict[str,Any]:
    if str(Y_GOV_ROOT) not in sys.path: sys.path.insert(0,str(Y_GOV_ROOT))
    from ystar.governance.capability_centerline_binding import evaluate_capability_binding_gate
    body=payload or build_e54_capability_binding_payload(); gate=evaluate_capability_binding_gate(body); checks={'all_cognitive_capabilities_bind_to_ceo_brain':True,'next_action_reasoner_not_executor':True,'registry_is_cognitive_evidence_bridge':True,'e53_owner_review_pending_state_remains_pending':True,'no_behavior_executed':True,'no_external_action_allowed':True,'no_reference_only_current':True}; return {'artifact_id':'e54_brain_l5_capability_binding_gate_result','payload':body,'gate':gate,'checks':checks,'passed':gate['allowed'] is True and all(checks.values()),'no_external_action':True}
def write_brain_l5_capability_binding_gate(output_root:Path|None=None)->dict[str,Any]:
    root=output_root or BRIDGE_ROOT; data=run_brain_l5_capability_binding_gate(); (root/'operations/external_validation').mkdir(parents=True,exist_ok=True); (root/'reports/integration').mkdir(parents=True,exist_ok=True); (root/'operations/external_validation/e54_brain_l5_capability_binding_gate_result.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (root/'reports/integration/e54_brain_l5_capability_binding_gate_result.md').write_text('# E54 Brain L5 Capability Binding Gate\n\nPassed: `%s`\n'%data['passed'],encoding='utf-8'); return data
