
from __future__ import annotations
import json, os
from pathlib import Path
from typing import Any
BRIDGE_ROOT=Path(os.environ.get('YSTAR_BRIDGE_LABS_ROOT', Path(__file__).resolve().parents[2]))
def build_capability_growth_metrics()->dict[str,Any]:
    return {'artifact_id':'e54_ceo_capability_growth_metrics','estimate_class':'artifact_supported_estimate','board_correction_count_estimate':7,'self_catch_count_estimate':5,'self_catch_rate':5/12,'repeated_failure_classes':['written_not_read_back','artifact_pile_without_runtime','owner_approval_boundary_risk'],'correction_sources':['Board explicit corrections','owner concern messages recorded in milestone summaries','anti-drift gate failures','capability binding failures','stale/readback failures','E53 pending-owner correction/guardrail events'],'capability_growth_evidence':['E50B counterfactual disconnection found and repaired','E50C brain written-not-read repaired','E51 anti-drift and binding gates','E52 proof packet no-overclaim/readback','E53 owner-review gate pending external action'],'remaining_weakness':['autonomous action loop not yet L5','real external feedback absent','behavior center not L5','K9 write integration not closed','real MCP transport not closed'],'future_metric_plan':{'structured_board_correction_event_required':True,'structured_ceo_self_catch_event_required':True,'formula':'self_catch / (self_catch + Board_corrections)','L5_threshold':'self_catch_rate >= 0.8 over recent major tasks and repeated P0 correction classes = 0'},'self_catch_metrics':{'self_catch_count_estimate':5,'self_catch_rate':5/12},'board_correction_metrics':{'board_correction_count_estimate':7},'no_external_action':True}
def write_capability_growth_metrics(output_root: Path | None=None)->dict[str,Any]:
    root=output_root or BRIDGE_ROOT; data=build_capability_growth_metrics(); (root/'operations/external_validation').mkdir(parents=True,exist_ok=True); (root/'reports/integration').mkdir(parents=True,exist_ok=True); (root/'operations/external_validation/e54_ceo_capability_growth_metrics.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8'); (root/'reports/integration/e54_ceo_capability_growth_metrics.md').write_text('# E54 CEO Capability Growth Metrics\n\nEstimate class: `artifact_supported_estimate`. Self-catch rate is not yet L5; future events must be structured.\n',encoding='utf-8'); return data
