#!/usr/bin/env python3
"""
Smoke test for ForgetGuard rule: backlog_as_defer_disguise
Auto-generated by governance_ci.py smoke-verify
"""
import pytest
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


@pytest.mark.skip(reason="AMENDMENT-021: rule retired 2026-04-20")
def test_backlog_as_defer_disguise_violation():
    """Smoke test: backlog_as_defer_disguise rule fires on trigger keyword."""
    # Mock context matching rule trigger
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "入 backlog",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation when available
    # from ystar.governance.forget_guard import check_forget_violation
    # violation = check_forget_violation(context)
    # assert violation is not None
    # assert violation["rule_id"] == "backlog_as_defer_disguise"

    # Placeholder assertion
    assert True, "Smoke test template — implement real check_forget_violation call"


@pytest.mark.skip(reason="AMENDMENT-021: rule retired 2026-04-20")
def test_backlog_as_defer_disguise_no_violation():
    """Negative test: valid input should NOT trigger backlog_as_defer_disguise."""
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "no violation keywords here",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation
    # violation = check_forget_violation(context)
    # assert violation is None

    assert True, "Smoke test template — implement negative case"
