#!/usr/bin/env python3
"""
Smoke test for ForgetGuard rule: dialogue_contract_drift
Auto-generated by governance_ci.py smoke-verify
"""
import pytest
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


def test_dialogue_contract_drift_violation():
    """Smoke test: dialogue_contract_drift rule fires on trigger keyword."""
    # Mock context matching rule trigger
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "test_keyword",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation when available
    # from ystar.governance.forget_guard import check_forget_violation
    # violation = check_forget_violation(context)
    # assert violation is not None
    # assert violation["rule_id"] == "dialogue_contract_drift"

    # Placeholder assertion
    assert True, "Smoke test template — implement real check_forget_violation call"


def test_dialogue_contract_drift_no_violation():
    """Negative test: valid input should NOT trigger dialogue_contract_drift."""
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "no violation keywords here",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation
    # violation = check_forget_violation(context)
    # assert violation is None

    assert True, "Smoke test template — implement negative case"
