#!/usr/bin/env python3
"""
Smoke test for ForgetGuard rule: cto_hourly_patrol_missed
Auto-generated by governance_ci.py smoke-verify
"""
import pytest
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


def test_cto_hourly_patrol_missed_violation():
    """Smoke test: cto_hourly_patrol_missed rule fires on trigger keyword."""
    # Mock context matching rule trigger
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "test_keyword",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation when available
    # from ystar.governance.forget_guard import check_forget_violation
    # violation = check_forget_violation(context)
    # assert violation is not None
    # assert violation["rule_id"] == "cto_hourly_patrol_missed"

    # Placeholder assertion
    assert True, "Smoke test template — implement real check_forget_violation call"


def test_cto_hourly_patrol_missed_no_violation():
    """Negative test: valid input should NOT trigger cto_hourly_patrol_missed."""
    context = {
        "agent_id": "ceo",
        "action_type": "tool_use",
        "action_payload": "no violation keywords here",
        "target_agent": None,
    }

    # TODO: Import real ForgetGuard check_violation
    # violation = check_forget_violation(context)
    # assert violation is None

    assert True, "Smoke test template — implement negative case"
